---
css: styles.css
---

# The South American MicroBiome Archive (saMBA)

The [South American Microbiome Archive (saMBA)](https://www.nature.com/articles/s41467-025-62601-4){.my_bold} is the largest archive of gut microbiome samples from South American populations analysed under an unified [workflow](https://github.com/Benjamin-Valderrama/saMBA-pipeline). 

The [article](https://www.nature.com/articles/s41467-025-62601-4) describes the process of gathering and analysing the microbiome data, as well as the main findings. The harmonised dataset can be downloaded from [Zenodo](https://zenodo.org/records/15050380) and the workflow used in the analysis is available on [GitHub](https://github.com/Benjamin-Valderrama/saMBA-pipeline/). All generated resources, including the article, are publicly available to propel microbiome research globally, specially in other neglected world regions.


The motivation to start this project is described [here](https://github.com/Benjamin-Valderrama/saMBA-pipeline/wiki/00.-About-the-project). If it resonated and you're interested in collaborating, please [get in touch](https://benjamin-valderrama.github.io/). 

# Plans for future developments

Below I share some ideas to expand saMBA. I made this public to keep the users informed and to invite people interested in contributing in any of these points to reach out.

::: bullet-list
-   Build an R package to facilitate the download of the outputs in Zenodo
-   ~~Implement the workflow as a Docker image so users can deploy it.~~
    -   [Update (01/Jun/2025)]{.my_bold}: Docker image [here](https://hub.docker.com/repository/docker/bvalderrama/samba/general)
-   Expand [saMBA]{.my_bold} (the resource) to include samples from other bodysites of southamericans.
-   Expand the workflow to include the analysis of projects using whole genome sequencing.
:::
